CREATE TABLE sources(
    id_sources integer NOT NULL generated always as identity (start with 30 increment by 1),
    id character varying(255),
    short character varying(255),
    city character varying(255),
    state character varying(255),
    country character varying(255),
    long character varying(255),
    id_city_name character varying(255),
    main character varying(255),
    center character varying(255),
    longitude double precision,
    latitude double precision,
    email character varying(255),
    contact character varying(255),
    who character varying(255),
    phone character varying(255),
    trees_per_source_count integer DEFAULT 0,
    country_code character varying(10),
    broken boolean DEFAULT false,
    broken_reason character varying(255),
    info text,
    download text,
    format character varying(255),
    filename character varying(255),
    gdal_options character varying(255),
    license character varying(255),
    modified timestamp without time zone,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE crosswalk(
  id_crosswalk integer NOT NULL generated always as identity (start with 30 increment by 1),
  id character varying(255),
  common character varying(255),
  species character varying(255),
  genus character varying(255),
  scientific character varying(255),
  family character varying(255),
  variety character varying(255),
  dbh character varying(255),
  height character varying(255),
  structure character varying(255),
  trunks character varying(255),
  age character varying(255),
  health character varying(255),
  crown character varying(255),
  spread character varying(255),
  planted character varying(255),
  updated character varying(255),
  location character varying(255),
  note character varying(255),
  address character varying(255),
  ref character varying(255),
  owner character varying(255),
  ule character varying(255),
  ule_min character varying(255),
  ule_max character varying(255),
  cost character varying(255),
  gps_date character varying(255),
  audited character varying(255),
  modified timestamp without time zone,
  created timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX id_idx ON sources (id);
ALTER TABLE ONLY crosswalk ADD CONSTRAINT crosswalk_id_fkey FOREIGN KEY (id) REFERENCES sources(id) ON UPDATE CASCADE ON DELETE CASCADE;

SELECT table_schema, table_name, column_name, data_type FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'sources';